// Generated by tools/gen_font.py ui. Do not edit.
// 4-bpp anti-aliased UI faces (high nibble = left pixel), plus the
// pre-rendered wordmark mask. See ui_font_t in ui_draw.h.
#pragma once
#include "ui_draw.h"

extern const ui_font_t ui_font_small;   // InterVariable.ttf Medium @14px
extern const ui_font_t ui_font_body;   // InterVariable.ttf Medium @18px
extern const ui_font_t ui_font_title;   // InterVariable.ttf SemiBold @22px
extern const ui_font_t ui_font_mono;   // JetBrainsMono-Regular.ttf Regular @18px
extern const ui_font_t ui_font_sas;   // InterVariable.ttf SemiBold @40px

#define UI_WORDMARK_W 153
#define UI_WORDMARK_H 28
extern const uint8_t img_wordmark[];   // core-keys InterVariable.ttf @30px, +1px tracking
