// Device Noise_KK responder over the vendor channel (docs/coauth-protocol.md §5).
#include <string.h>
#include "esp_log.h"
#include "noise/protocol.h"
#include "ckvp.h"
#include "session.h"
#include "corekeys.h"
#include "lcd.h"

static const char *TAG = "session";

// Fixed bring-up keys (NO pairing yet): the device's own X25519 private and the
// daemon's pinned public. Generated by `cargo run --example gen_keys`. Real
// pairing derives and pins these (§4).
static const uint8_t CK_DEVICE_PRIV[32] = {
    0x10, 0xa1, 0x8e, 0x4f, 0x06, 0xcb, 0x47, 0x3c, 0x06, 0x4a, 0xb4, 0x1f,
    0x36, 0x80, 0xc7, 0x71, 0xa1, 0xf5, 0x43, 0x2a, 0xbe, 0xeb, 0xd1, 0x50,
    0x9a, 0x08, 0x5d, 0x84, 0x9d, 0xd4, 0xeb, 0x04,
};
static const uint8_t CK_DAEMON_PUB[32] = {
    0x4e, 0x6d, 0x2a, 0x36, 0x38, 0x32, 0xae, 0x81, 0x73, 0xfa, 0x7d, 0x1a,
    0xf2, 0x54, 0xac, 0x7d, 0x22, 0x49, 0xb7, 0xc7, 0xf3, 0xa2, 0x68, 0xc0,
    0x5c, 0xf3, 0xd6, 0x0e, 0x4f, 0x7f, 0x05, 0x31,
};

enum { ST_IDLE = 0, ST_HANDSHAKING = 1, ST_TRANSPORT = 2 };
static int s_state = ST_IDLE;
static NoiseCipherState *s_send, *s_recv;
static uint16_t s_chan = 1;

int session_state(void) { return s_state; }

// ckvp_encode emit target: send one report on the vendor interface.
static void emit_vendor(const uint8_t report[CKVP_REPORT])
{
    ck_report_send(ITF_VENDOR, report);
}

static void reset_session(void)
{
    if (s_send) { noise_cipherstate_free(s_send); s_send = 0; }
    if (s_recv) { noise_cipherstate_free(s_recv); s_recv = 0; }
    s_state = ST_IDLE;
}

// Run the KK responder: consume msg1, produce+send msg2, split into transport.
static void do_handshake(const uint8_t *msg1, uint16_t len)
{
    reset_session();
    s_state = ST_HANDSHAKING;

    NoiseHandshakeState *hs = 0;
    if (noise_handshakestate_new_by_name(&hs, "Noise_KK_25519_ChaChaPoly_SHA256",
                                         NOISE_ROLE_RESPONDER) != NOISE_ERROR_NONE) {
        ESP_LOGE(TAG, "hs new failed"); s_state = ST_IDLE; return;
    }
    NoiseDHState *ldh = noise_handshakestate_get_local_keypair_dh(hs);
    noise_dhstate_set_keypair_private(ldh, CK_DEVICE_PRIV, 32);
    NoiseDHState *rdh = noise_handshakestate_get_remote_public_key_dh(hs);
    noise_dhstate_set_public_key(rdh, CK_DAEMON_PUB, 32);

    if (noise_handshakestate_start(hs) != NOISE_ERROR_NONE) {
        ESP_LOGE(TAG, "hs start failed"); noise_handshakestate_free(hs); s_state = ST_IDLE; return;
    }

    uint8_t inbuf[512], outbuf[512];
    NoiseBuffer mb;
    if (len > sizeof(inbuf)) { noise_handshakestate_free(hs); s_state = ST_IDLE; return; }
    memcpy(inbuf, msg1, len);
    noise_buffer_set_input(mb, inbuf, len);
    if (noise_handshakestate_read_message(hs, &mb, NULL) != NOISE_ERROR_NONE) {
        ESP_LOGW(TAG, "read msg1 failed"); noise_handshakestate_free(hs); s_state = ST_IDLE; return;
    }

    noise_buffer_set_output(mb, outbuf, sizeof(outbuf));
    if (noise_handshakestate_write_message(hs, &mb, NULL) != NOISE_ERROR_NONE) {
        ESP_LOGW(TAG, "write msg2 failed"); noise_handshakestate_free(hs); s_state = ST_IDLE; return;
    }
    ckvp_encode(CK_MT_NOISE_HS, s_chan, outbuf, mb.size, emit_vendor);

    if (noise_handshakestate_split(hs, &s_send, &s_recv) != NOISE_ERROR_NONE) {
        ESP_LOGE(TAG, "split failed"); noise_handshakestate_free(hs); s_state = ST_IDLE; return;
    }
    noise_handshakestate_free(hs);
    s_state = ST_TRANSPORT;
    ESP_LOGI(TAG, "Noise session up");
    ui_note_ctap("session up");
}

// Transport record: decrypt and (bring-up) echo it back encrypted.
static void do_transport(const uint8_t *data, uint16_t len)
{
    if (s_state != ST_TRANSPORT || !s_recv || !s_send) return;
    uint8_t buf[CKVP_MAX_MSG];
    if (len > sizeof(buf)) return;
    memcpy(buf, data, len);

    NoiseBuffer b;
    noise_buffer_set_inout(b, buf, len, sizeof(buf));
    if (noise_cipherstate_decrypt(s_recv, &b) != NOISE_ERROR_NONE) {
        ESP_LOGW(TAG, "decrypt failed (dropped)"); // droppable, not fatal (§5)
        return;
    }
    // Re-encrypt the same plaintext and send it back.
    noise_buffer_set_inout(b, buf, b.size, sizeof(buf));
    if (noise_cipherstate_encrypt(s_send, &b) != NOISE_ERROR_NONE) return;
    ckvp_encode(CK_MT_NOISE_MSG, s_chan, buf, b.size, emit_vendor);
    ui_note_ctap("echo");
}

void session_on_message(uint8_t msg_type, const uint8_t *data, uint16_t len, uint16_t chan)
{
    s_chan = chan;
    switch (msg_type) {
    case CK_MT_NOISE_HS:
        do_handshake(data, len);
        break;
    case CK_MT_NOISE_MSG:
        do_transport(data, len);
        break;
    default:
        // Pairing messages come later; ignore for bring-up.
        break;
    }
}
