#!/usr/bin/env python3
"""Render a monospace TTF into an 8x16 1-bpp C font table for the mule LCD.

Emits main/font8x16.h with `const uint8_t font8x16[95][16]` covering ASCII
0x20..0x7E, one byte per row (bit 7 = leftmost pixel). Cosmetic only — any glyph
imperfection shows on screen but cannot crash the firmware.

Requires: pip install pillow
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

CANDIDATES = [
    "/System/Library/Fonts/Menlo.ttc",
    "/System/Library/Fonts/SFNSMono.ttf",
    "/Library/Fonts/DejaVuSansMono.ttf",
    "/System/Library/Fonts/Monaco.ttf",
]
W, H = 8, 16
FIRST, LAST = 0x20, 0x7E

def load_font():
    for path in CANDIDATES:
        if not os.path.exists(path):
            continue
        for size in range(16, 10, -1):
            try:
                f = ImageFont.truetype(path, size)
            except Exception:
                continue
            # accept the largest size whose widest glyph fits the 8px cell
            wmax = max(f.getbbox(chr(c))[2] for c in range(FIRST, LAST + 1) if f.getbbox(chr(c)))
            if wmax <= W:
                return f, path, size
    sys.exit("no usable monospace TTF found; edit CANDIDATES")

def render(font):
    rows = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("1", (W, H), 0)
        d = ImageDraw.Draw(img)
        ch = chr(code)
        bbox = font.getbbox(ch)
        # center horizontally, sit on a consistent baseline
        gw = (bbox[2] - bbox[0]) if bbox else 0
        x = max(0, (W - gw) // 2 - (bbox[0] if bbox else 0))
        d.text((x, 1), ch, font=font, fill=1)
        glyph = []
        px = img.load()
        for y in range(H):
            b = 0
            for xx in range(W):
                if px[xx, y]:
                    b |= 1 << (7 - xx)
            glyph.append(b)
        rows.append((code, ch, glyph))
    return rows

def main():
    font, path, size = load_font()
    rows = render(font)
    out = os.path.join(os.path.dirname(__file__), "..", "firmware", "mule-esp32s3", "main", "font8x16.h")
    out = os.path.abspath(out)
    with open(out, "w") as f:
        f.write("// Generated by tools/gen_font.py from %s @ %dpx. Do not edit.\n" % (os.path.basename(path), size))
        f.write("// ASCII 0x20..0x7E, 8x16, one byte/row, bit7 = leftmost pixel.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define FONT_FIRST 0x%02X\n#define FONT_LAST 0x%02X\n" % (FIRST, LAST))
        f.write("#define FONT_W 8\n#define FONT_H 16\n\n")
        f.write("static const uint8_t font8x16[%d][16] = {\n" % len(rows))
        for code, ch, glyph in rows:
            label = ch if ch != "\\" else "backslash"
            f.write("    { %s }, // 0x%02X '%s'\n" %
                    (", ".join("0x%02X" % b for b in glyph), code, label if ch not in '"\\' else '?'))
        f.write("};\n")
    print("wrote", out, "from", path, "size", size)

if __name__ == "__main__":
    main()
