#!/usr/bin/env python3
"""Font table generator for the mule LCD. Two modes:

  gen_font.py            legacy: 8x16 1-bpp Menlo table -> main/font8x16.h
  gen_font.py ui         UI faces: 4-bpp anti-aliased tables -> main/fonts.{h,c}

The `ui` mode renders the vendored TTFs in tools/fonts/ at 4x and box-filters
down to 16 alpha levels, at the final pixel size (no runtime scaling). Each
face stores per-glyph advance / ink-width / x-bearing / byte-offset plus packed
4-bpp rows (high nibble = left pixel), cell_h rows per glyph. Also emits the
pre-rendered "core-keys" wordmark mask. Cosmetic only - glyph imperfections
show on screen but cannot crash the firmware.

Requires: pip install pillow
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
FONT_DIR = os.path.join(ROOT, "tools", "fonts")
OUT_DIR = os.path.join(ROOT, "firmware", "mule-esp32s3", "main")

FIRST, LAST = 0x20, 0x7E

# ---- legacy 8x16 1-bpp table (unchanged behavior) ---------------------------

CANDIDATES = [
    "/System/Library/Fonts/Menlo.ttc",
    "/System/Library/Fonts/SFNSMono.ttf",
    "/Library/Fonts/DejaVuSansMono.ttf",
    "/System/Library/Fonts/Monaco.ttf",
]
W, H = 8, 16

def load_font():
    for path in CANDIDATES:
        if not os.path.exists(path):
            continue
        for size in range(16, 10, -1):
            try:
                f = ImageFont.truetype(path, size)
            except Exception:
                continue
            # accept the largest size whose widest glyph fits the 8px cell
            wmax = max(f.getbbox(chr(c))[2] for c in range(FIRST, LAST + 1) if f.getbbox(chr(c)))
            if wmax <= W:
                return f, path, size
    sys.exit("no usable monospace TTF found; edit CANDIDATES")

def render(font):
    rows = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("1", (W, H), 0)
        d = ImageDraw.Draw(img)
        ch = chr(code)
        bbox = font.getbbox(ch)
        # center horizontally, sit on a consistent baseline
        gw = (bbox[2] - bbox[0]) if bbox else 0
        x = max(0, (W - gw) // 2 - (bbox[0] if bbox else 0))
        d.text((x, 1), ch, font=font, fill=1)
        glyph = []
        px = img.load()
        for y in range(H):
            b = 0
            for xx in range(W):
                if px[xx, y]:
                    b |= 1 << (7 - xx)
            glyph.append(b)
        rows.append((code, ch, glyph))
    return rows

def main_legacy():
    font, path, size = load_font()
    rows = render(font)
    out = os.path.join(OUT_DIR, "font8x16.h")
    with open(out, "w") as f:
        f.write("// Generated by tools/gen_font.py from %s @ %dpx. Do not edit.\n" % (os.path.basename(path), size))
        f.write("// ASCII 0x20..0x7E, 8x16, one byte/row, bit7 = leftmost pixel.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define FONT_FIRST 0x%02X\n#define FONT_LAST 0x%02X\n" % (FIRST, LAST))
        f.write("#define FONT_W 8\n#define FONT_H 16\n\n")
        f.write("static const uint8_t font8x16[%d][16] = {\n" % len(rows))
        for code, ch, glyph in rows:
            label = ch if ch != "\\" else "backslash"
            f.write("    { %s }, // 0x%02X '%s'\n" %
                    (", ".join("0x%02X" % b for b in glyph), code, label if ch not in '"\\' else '?'))
        f.write("};\n")
    print("wrote", out, "from", path, "size", size)

# ---- UI faces: 4-bpp anti-aliased, generated at final size ------------------

SS = 4  # supersampling factor

INTER = os.path.join(FONT_DIR, "InterVariable.ttf")
JBMONO = os.path.join(FONT_DIR, "JetBrainsMono-Regular.ttf")

# name, ttf, named-instance (None = as-is), px, cell_h, fixed_adv (0 = proportional),
# subset (None = full ASCII), center_in_adv (tabular digits)
FACES = [
    ("small", INTER, "Medium",   14, 18, 0,  None,         False),
    ("body",  INTER, "Medium",   18, 24, 0,  None,         False),
    ("title", INTER, "SemiBold", 22, 29, 0,  None,         False),
    ("mono",  JBMONO, None,      18, 24, 11, None,         False),
    ("sas",   INTER, "SemiBold", 40, 44, 24, "0123456789", True),
]
WORDMARK = ("core-keys", INTER, "SemiBold", 30, 1)  # text, ttf, instance, px, tracking px

def open_face(ttf, instance, px):
    f = ImageFont.truetype(ttf, px * SS)
    if instance:
        f.set_variation_by_name(instance)
    return f

def render_glyph_l(font, ch, canvas_w, canvas_h, pen_x, base_y):
    img = Image.new("L", (canvas_w, canvas_h), 0)
    ImageDraw.Draw(img).text((pen_x, base_y), ch, font=font, fill=255, anchor="ls")
    return img

def downsample(img):
    return img.resize((img.width // SS, img.height // SS), Image.BOX)

def ink_bbox(img):
    return img.getbbox()  # (x0, y0, x1, y1) or None

def build_face(name, ttf, instance, px, cell_h, fixed_adv, subset, center):
    font = open_face(ttf, instance, px)
    ascent, descent = font.getmetrics()
    chars = subset if subset else "".join(chr(c) for c in range(FIRST, LAST + 1))
    canvas_w, canvas_h = px * SS * 3, px * SS * 3
    pen4 = px * SS       # pen x in the 4x canvas (divisible by SS)
    base_y = px * SS * 2  # baseline row in the 4x canvas

    glyphs = {}
    top_min, bot_max = 10 ** 9, -10 ** 9
    for ch in chars:
        img = downsample(render_glyph_l(font, ch, canvas_w, canvas_h, pen4, base_y))
        bb = ink_bbox(img)
        adv = font.getlength(ch) / SS
        glyphs[ch] = (img, bb, adv)
        if bb:
            top_min = min(top_min, bb[1])
            bot_max = max(bot_max, bb[3])
    base_final = base_y // SS
    ink_h = bot_max - top_min
    if ink_h > cell_h:
        sys.exit("face %s: ink height %d exceeds cell %d" % (name, ink_h, cell_h))
    # center the union ink block in the cell
    cell_top = top_min - (cell_h - ink_h) // 2
    baseline = base_final - cell_top

    adv_l, gw_l, xoff_l, off_l, blob = [], [], [], [], bytearray()
    for ch in chars:
        img, bb, adv = glyphs[ch]
        a = int(round(adv)) if not fixed_adv else fixed_adv
        if bb:
            x0, x1 = bb[0], bb[2]
            gw = x1 - x0
            xoff = (a - gw) // 2 if center else x0 - pen4 // SS
        else:
            gw, xoff = 0, 0
        adv_l.append(a); gw_l.append(gw); xoff_l.append(xoff); off_l.append(len(blob))
        if gw:
            crop = img.crop((bb[0], cell_top, bb[2], cell_top + cell_h))
            p = crop.load()
            for y in range(cell_h):
                for x in range(0, gw, 2):
                    hi = (p[x, y] * 15 + 127) // 255
                    lo = (p[x + 1, y] * 15 + 127) // 255 if x + 1 < gw else 0
                    blob.append((hi << 4) | lo)
    if max(off_l) > 0xFFFF:
        sys.exit("face %s: offsets exceed uint16" % name)
    first = ord(chars[0])
    return {
        "name": name, "first": first, "last": ord(chars[-1]), "cell_h": cell_h,
        "baseline": baseline, "fixed_adv": fixed_adv, "prop": not fixed_adv,
        "adv": adv_l, "gw": gw_l, "xoff": xoff_l, "off": off_l, "blob": bytes(blob),
        "src": "%s %s @%dpx" % (os.path.basename(ttf), instance or "Regular", px),
    }

def build_wordmark():
    text, ttf, instance, px, track = WORDMARK
    font = open_face(ttf, instance, px)
    w4 = int(font.getlength(text)) + px * SS
    img = Image.new("L", (w4 + len(text) * track * SS, px * SS * 3), 0)
    d = ImageDraw.Draw(img)
    x = px * SS // 2
    for ch in text:
        d.text((x, px * SS * 2), ch, font=font, fill=255, anchor="ls")
        x += int(font.getlength(ch)) + track * SS
    img = downsample(img)
    bb = ink_bbox(img)
    img = img.crop(bb)
    p = img.load()
    blob = bytearray()
    for y in range(img.height):
        for x in range(0, img.width, 2):
            hi = (p[x, y] * 15 + 127) // 255
            lo = (p[x + 1, y] * 15 + 127) // 255 if x + 1 < img.width else 0
            blob.append((hi << 4) | lo)
    return img.width, img.height, bytes(blob)

def emit_bytes(f, data, per_line=24):
    for i in range(0, len(data), per_line):
        f.write("    " + ",".join(str(b) for b in data[i:i + per_line]) + ",\n")

def main_ui():
    faces = [build_face(*spec) for spec in FACES]
    wm_w, wm_h, wm_blob = build_wordmark()

    hdr = os.path.join(OUT_DIR, "fonts.h")
    with open(hdr, "w") as f:
        f.write("// Generated by tools/gen_font.py ui. Do not edit.\n")
        f.write("// 4-bpp anti-aliased UI faces (high nibble = left pixel), plus the\n")
        f.write("// pre-rendered wordmark mask. See ui_font_t in ui_draw.h.\n")
        f.write("#pragma once\n#include \"ui_draw.h\"\n\n")
        for fc in faces:
            f.write("extern const ui_font_t ui_font_%s;   // %s\n" % (fc["name"], fc["src"]))
        f.write("\n#define UI_WORDMARK_W %d\n#define UI_WORDMARK_H %d\n" % (wm_w, wm_h))
        f.write("extern const uint8_t img_wordmark[];   // %s %s @%dpx, +%dpx tracking\n"
                % (WORDMARK[0], os.path.basename(WORDMARK[1]), WORDMARK[3], WORDMARK[4]))

    src = os.path.join(OUT_DIR, "fonts.c")
    total = 0
    with open(src, "w") as f:
        f.write("// Generated by tools/gen_font.py ui. Do not edit.\n")
        f.write("#include \"fonts.h\"\n\n")
        for fc in faces:
            n, cnt = fc["name"], len(fc["adv"])
            total += len(fc["blob"]) + cnt * 5
            f.write("// %s: %d glyphs, %d bytes\n" % (fc["src"], cnt, len(fc["blob"])))
            if fc["prop"]:
                f.write("static const uint8_t %s_adv[%d] = {\n" % (n, cnt)); emit_bytes(f, fc["adv"]); f.write("};\n")
            f.write("static const uint8_t %s_gw[%d] = {\n" % (n, cnt)); emit_bytes(f, fc["gw"]); f.write("};\n")
            f.write("static const int8_t %s_xoff[%d] = {\n" % (n, cnt)); emit_bytes(f, fc["xoff"]); f.write("};\n")
            f.write("static const uint16_t %s_off[%d] = {\n" % (n, cnt)); emit_bytes(f, fc["off"], 16); f.write("};\n")
            f.write("static const uint8_t %s_px[%d] = {\n" % (n, len(fc["blob"]))); emit_bytes(f, fc["blob"]); f.write("};\n")
            f.write("const ui_font_t ui_font_%s = { 0x%02X, 0x%02X, %d, %d, %d, %s, %s_gw, %s_xoff, %s_off, %s_px };\n\n"
                    % (n, fc["first"], fc["last"], fc["cell_h"], fc["baseline"], fc["fixed_adv"],
                       ("%s_adv" % n) if fc["prop"] else "0", n, n, n, n))
        total += len(wm_blob)
        f.write("// wordmark mask %dx%d, %d bytes\n" % (wm_w, wm_h, len(wm_blob)))
        f.write("const uint8_t img_wordmark[%d] = {\n" % len(wm_blob)); emit_bytes(f, wm_blob); f.write("};\n")
    print("wrote", hdr)
    print("wrote", src, "(~%.1f KB of tables)" % (total / 1024.0))
    for fc in faces:
        print("  %-6s cell %2d baseline %2d %s %5d B" %
              (fc["name"], fc["cell_h"], fc["baseline"],
               ("adv %2d" % fc["fixed_adv"]) if fc["fixed_adv"] else "prop  ", len(fc["blob"])))
    print("  wordmark %dx%d %d B" % (wm_w, wm_h, len(wm_blob)))

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "ui":
        main_ui()
    else:
        main_legacy()
